app/controllers/staypuft/bonds_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1179695
Change the default bonding mode from balance-tlb to active-backup.

BZ #1179695: Make active-backup the default bonding mode

---

app/controllers/staypuft/bonds_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1177740
This will also fix for the other operations (adding additional
interfaces, deleting interfaces, etc.). The list of hosts was not being
parsed properly. Therefore, only one of the hosts was being operated
upon. When the user went back into the settings, it would reset to
whatever setting the first host has, which may not have been what was
selected.

BZ #1177740: Fix bond mode selection for multiple hosts

---

app/controllers/staypuft/bonds_controller.rb
app/views/staypuft/interfaces/_drop_zone.html.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1181327
The change_mode was not passing host_ids the same way as the rest of the
operations. This makes the change_mode call correct.

BZ #1181327: Revert previous change_mode "fix", and fix properly

---

app/assets/javascripts/staypuft/staypuft.js
app/lib/staypuft/seeder.rb
app/models/staypuft/deployment/glance_service.rb
app/views/staypuft/steps/services_configuration.html.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1180694
When Ceph is selected as the backend for glance, this code does a number
of things:
1. The seeder now uses glance_service.ceph_backend? to set the
include_glance param
2. It puts up a message warning the user that manual steps are required.
3. The user would then override the advanced config to make
include_glance explicitly 'true' and get rid of the dynamic param.

BZ #1180694: Initially disable glance when using ceph as a backend

---

app/lib/actions/staypuft/deployment/deploy.rb
app/lib/actions/staypuft/hostgroup/ordered_deploy.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1179915
Compute nodes don't handle fully parallel deployment, one compute node
needs to be deployed on its own and then the rest can be deployed in
parallel.

BZ #1179915 - nova-manage network create novanetwork called twice

---

app/lib/actions/staypuft/hostgroup/ordered_deploy.rb

This is a regression introduced with the puppetssh
functionality, partially fixed with PR #400, and this
makes the final addition to support all 3 modes

added orchestration handling for 'serial' deployment.

---

staypuft.gemspec

We are releasing Discovery 2.0 and Staypuft insist on 1.4 version. I'd
recommend to go either for `> 1.4.0` (which gives a warning for me) or drop the
version number completely.
This blocks us from the release, can I ask you for a quick minor version?
Thank you

Dropping hard request on discovery gem

---

app/lib/actions/staypuft/host/report_wait.rb
app/lib/actions/staypuft/host/wait_until_provisioned.rb
app/lib/actions/staypuft/host/wait_until_ready.rb
app/lib/actions/staypuft/middleware/timeout.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1184630
Implement timeouts for actions which do polling. Note that if DynFlow
executor stops working, the timeout checking will stop working too,
and the deployment will still run forever. This patch mitigates issues
like Puppet not being triggered, provisioning failures etc., but not
DynFlow failures.

BZ#1184630 - deployments run forever

---

app/assets/javascripts/staypuft/staypuft.js
app/lib/staypuft/seeder.rb
app/models/staypuft/deployment/cinder_service.rb
app/models/staypuft/deployment/cinder_service/netapp.rb
app/views/staypuft/steps/_cinder.html.erb
app/views/staypuft/steps/_cinder_netapp_form.html.erb

Enables a user to use NetApp storage systems as backends for Cinder.
I was able successfully create a deployment configuration with the new NetApp parameters, but my development environment wasn't able to actually complete any deployments.

Enable NetApp driver for Cinder

---

app/models/staypuft/deployment.rb

instead of hardcoding a specific version

rhbz#1189307 enable latest RHEL by default

---

app/lib/actions/staypuft/host/puppet_run.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1184633
Previously PuppetRun errors were visible in dynflow console only if the
PuppetRun action failed because of them. Now the errors will be saved
anytime an attempt fails, even if a later attempt succeeds.

Related to BZ#1184633 - report errors from 1st and 2nd attempt too

---

app/lib/actions/staypuft/host/trigger_provisioning.rb
app/models/staypuft/concerns/environment_extensions.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1180322
Even though the client registration Puppet run doesn't apply any
changes, it still attempts to compile the full host's Puppet catalog and
may cause errors. Switching it to an empty environment will exclude the
Puppet classes from the YAML description of the node and cause the
catalog to be empty and without errors.

BZ#1180322 - registration puppet run reports errors

---

app/models/staypuft/deployment/cinder_service.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1192152
Some of the netapp compute_* methods had different names and had to be
handle in a different way.

BZ #1192152: Netapp compute method names were incorrect

---

app/assets/stylesheets/staypuft/staypuft.css.scss

Minor issue with CSS label not clearing left

---

app/lib/staypuft/seeder.rb

Ceph Public Network should be set to be the Storage network, not the PXE.

BZ#1192864: Ceph Public Network has to be Storage

---

app/models/staypuft/concerns/nic_bonding_extensions.rb
lib/staypuft/engine.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1188602
Changes to bonds will not save without a mac address. This will set the
mac address to the first interface in the bond.

BZ #1188602: Ensure bonds have a mac address

---

app/lib/staypuft/seeder.rb
app/models/staypuft/deployment/cinder_service.rb
app/models/staypuft/deployment/cinder_service/netapp.rb

This change fixes a few things:
1. Change storage_families param to storage_familys. No need
to complicate the code because of English grammar.
2. Split nfs_shares param by comma to an array because this
is what puppet-cinder expects

Staypuft-NetApp fixes

---

app/lib/staypuft/seeder.rb

Change nova_host to use nova_private_vip, and add
vncproxy_host to stick with nova_public_vip

bug 1193448: separate nova_host and vncproxy_host

---

app/lib/staypuft/network_query.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1221018
Because of the way Foreman handles the primary interface, and when
the tenant network is on that interface, with no bond or vlan involved,
it would cause an exception.

BZ #1221018: Account for tenant network on primary interface

---

app/assets/javascripts/staypuft/staypuft.js
app/lib/staypuft/seeder.rb
app/models/staypuft/deployment/neutron_service.rb
app/views/staypuft/steps/_neutron.html.erb

While creating a deployment, users can now select Cisco N1Kv
as an ML2 mech driver option. Checking the Cisco N1Kv option
would bring up text boxes that would accept values for N1Kv
VSM IP and password.
BZ# 1250271: Cisco Nexus 1000V does not show up among ML2 drivers
while creating deployment
https://bugzilla.redhat.com/show_bug.cgi?id=1250271

Add checkbox for cisco n1kv and boxes for vsm info
